### ISSUE TITLE
After install and config, getting "[custom_components.sia] list index out of range"

### ISSUE THREAD

**Issue by jh83** [eavanvalkenburg/sia#3]
Just installed this component thru HACS and do receive an error saying:

![image](https://user-images.githubusercontent.com/16517831/65352495-1e14fc00-dbeb-11e9-894a-db668d685ebb.png)

Apart from this, Ajax app is unable to connect. It was able to connect when running the cheaterdev version (but then failing multiple zones, and therefore testing your version thru HACS).

HASSIO version: 0.99.2

## Configuration

sia:
  port:  8231
  hubs:
    - name: Alarm
      account: AA

## Describe the bug
After installing, error message is shown under developer > logs view. The error message says 

Log Details (ERROR)
Fri Sep 20 2019 21:13:20 GMT+0200 (Central European Summer Time)
list index out of range

## Debug log

2019-09-20 21:23:47 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:23:48 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:23:48 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:23:48 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:24:49 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:24:51 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:24:51 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:24:51 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:25:53 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:25:54 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:25:54 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:25:54 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:26:56 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:26:57 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:26:57 ERROR (Thread-4) [custom_components.sia] list index out of range
2019-09-20 21:26:57 ERROR (Thread-4) [custom_components.sia] list index out of range

**Comment by eavanvalkenburg** [comment]
Should be fixed now, give it a try!

**Comment by jh83** [comment]
I'm sorry. But the issue remains.

I upgraded the component thru hacs. But it still gives the same error message.

**Comment by josefpihlstrom** [comment]
I had this same issue but was resolved once I updated my configuration yaml with ping_interval and encryption_key. I had to activate encryption and add a key in my ajax system as well and then I stopped receiving this message.

**Comment by jh83** [comment]
Tried specifying both encryption_key and ping_interval like this

sia:
  port:  8231
  hubs:
    - name: Alarm
      account: AA
      encryption_key: AAAAAAAAAAAAAAEB0F5CCFEA11E751D1
      ping_interval: 1

But now a new error has appeared saying "subsection not found".

@josefpihlstrom , is there any difference in your config compared to mine?

**Comment by jh83** [comment]
@eavanvalkenburg , i managed to get it running by adding both encryption_key and ping_interval. 

At first, the error remained and a new one was seen (see previous post). But then i tried to change the enctyption_key to 16 characters instead of 32 and then it started working.  - Maybe a bug since Ajax alows me to have a longer key, but the SIA component that you have developed does not?

**Comment by eavanvalkenburg** [comment]
Hi, it is in the install manual for this component that the key should be 16 characters, but I'm looking into if that can be flexible, keep you posted and glad it works for now at least!

**Comment by eavanvalkenburg** [comment]
I think I made a fix for this, please try, I've also made the debugging logging a bit more verbose, so please post additional logs if you still have an error.
